### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by sunnyzhifei** [colin-han/dingding-gitlab-robot#1]
i want try to use ,but i dont know how

**Comment by colin-han** [comment]
Wait a couple of days, I'll add readme for you :) . Thanks for you interesting

**Comment by colin-han** [comment]
Hi, Sunny,

I just found there already has an official robot for gitlab in dingtalk. Please see a reference in https://ding-doc.dingtalk.com/doc#/serverapi2/hoy7iv

**Comment by sunnyzhifei** [comment]
Hi Colin,


thanks . I have tried it before ,but its failed when job or pipline events. just push event is ok&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Colin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 上午9:50
收件人:&nbsp;"colin-han/dingding-gitlab-robot"<dingding-gitlab-robot@noreply.github.com&gt;;
抄送:&nbsp;"sunnyzhifei"<sunny_zhifei@163.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [colin-han/dingding-gitlab-robot] how to use? (#1)





 
Hi, Sunny,
 
I just found there already has an official robot for gitlab in dingtalk. Please see a reference in https://ding-doc.dingtalk.com/doc#/serverapi2/hoy7iv

**Comment by colin-han** [comment]
Oh, see.

Maybe you can check the SDK for dingtalk. I think it is not so complex. This project is simple, but it is very old too. I'm not sure I can remember how to use it. I still need to read the SDK again. Sorry for I cannot help you more. :-(

**Comment by sunnyzhifei** [comment]
ok.thank you very much~



---Original---
